.TH "lsl::lost_error" 3 "Fri May 10 2019" "lslsub_dbfeeder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsl::lost_error \- Exception class that indicates that a stream inlet's source has been irrecoverably lost\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lsl_cpp\&.h>\fP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlost_error\fP (const std::string &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception class that indicates that a stream inlet's source has been irrecoverably lost\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lsl::lost_error::lost_error (const std::string & msg)\fC [inline]\fP, \fC [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for lslsub_dbfeeder from the source code\&.
